### ISSUE TITLE
[Docs] Wrong example values under Parsing/Table of tokens

### ISSUE THREAD

**Issue by ysrn** [moment/luxon#1087]
URL: https://moment.github.io/luxon/#/parsing?id=table-of-tokens

The H row shows "9" instead of "13".
The D row shows a date other than the sample parsed one.
The t row shows a time other than the sample parsed one.

Seems like those are forgotten values from when the sample date was different.

**Comment by icambron** [comment]
Thanks, fixed in 1899cc007780ba84af3ed87becc83c4097b6a335

**Comment by ysrn** [comment]
Still broken, just in a different way now :)
I commented on the commit.
