### ISSUE TITLE
Bug returning monthShort and monthLong

### ISSUE THREAD

**Issue by johnnydimas** [moment/luxon#204]
I have an issue where monthShort and monthLong are not returning the correct data from my date time object. I am using luxon in nodejs 8.9.3.

```
const { DateTime } = require('luxon');

const today = DateTime.local();
const monthLong = today.monthLong;
const monthShort = today.monthShort;

console.log(monthLong) => 'M03'
console.log(monthShort) => 'M03'

```
The expected results should be 'March' and 'Mar'.

If I do the following, I get the correct response:

```
const monthShort = today.toFormat('MMM');
console.long(monthShort) => 'Mar'
```

Thanks!

**Comment by icambron** [comment]
Yeah, so the default locale in Node is sometime set to null. (On OSX, where I developed this, it was set to "en", but now that I'm running Linux, I see that isn't universal.) At any rate, the quick fix is this:

```js
const { Settings } = require('luxon');
Settings.defaultLocale = 'en-us';
```

I'm going to do a bit of work to make that smoother on a clean Node instance. No one wants "M03" as an output to anything. I'll leave this open.

**Comment by icambron** [comment]
Fixed in 2eaa5d7, will release soon.

**Comment by lookapanda** [comment]
Hello,

this issue is not fixed yet somehow.

https://repl.it/repls/HealthySolidBusinesssoftware

As you can see, it still outputs weirdly.
