### ISSUE TITLE
Number `Infinity` not supported

### ISSUE THREAD

**Issue by cooperka** [moment/luxon#291]
I came across this issue trying to invoke `DateTime.fromMillis(updatedAt).plus(duration.CACHE_TTL)`, a simple way of calculating whether cached data is stale or not. I can set `CACHE_TTL` to `Infinity` during dev to prevent the cache from expiring. Unfortunately Luxon doesn't support this, even though technically `typeof Infinity === 'number'`.

So far I've tracked it down to the implementation of [`fromMillis`](https://github.com/moment/luxon/blob/master@{2018-07-09}/src/duration.js#L217) which is called by [`friendlyDuration`](https://github.com/moment/luxon/blob/master@{2018-07-09}/src/duration.js#L155), but I ran out of time to debug. I'll attempt to continue in a few days.

Happy to submit a PR, though I'm not sure what the consequences of supporting this number would be -- is there such thing as an "infinite" future, or do we have to pick some date arbitrarily far away?

**Comment by cooperka** [comment]
As a workaround, using `Number.MAX_SAFE_INTEGER` instead of `Infinity` seems to work... ish. It results in a DateTime object with:

```
{
  ts: 0NaN-NaN-NaNTNaN:NaN:NaN.NaN-NaN:NaN,
}
```

which is greater than `DateTime.local()` using the `>` operator. It works for my use case.

**Comment by icambron** [comment]
Javascript dates can only represent times up to `8640000000000000` (100 million days after epoch start), which is slightly smaller than `Number.MAX_SAFE_INTEGER`. I don't want to cap all math at that number (would lead to really odd behavior in other scenarios), but I'd be open to saying that if the Infinity comes in, we can cap at the max possible date (same on the negative side)

**Comment by gampleman** [comment]
It seems from some of my testing that Luxon supports smaller dates than the native date. It would be nice to have some constants that support maximum and minimum safe dates. For example if one wants to (de)serialize dates to ISO format, than it seems like the maximum safe date is `DateTime.fromMillis(253402300799999)`.

<details>
  <summary>I obtained this number with this binary search</summary>

```javascript
function binarySearch(min, max, cond) {
  const midPoint = Math.floor((max - min) / 2);
  if (min === midPoint) {
    return midPoint;
  } 
  if (cond(midPoint)) {
    return binarySearch(midPoint, max, cond);
  } else {
    return binarySearch(min, midPoint, cond);
  }
}

binarySearch(0, 8640000000000000, ms => DateTime.fromISO(DateTime.fromMillis(ms).toISO()).isValid)
```

</details>

**Comment by icambron** [comment]
@gampleman if Luxon doesn't support the full range of dates that the native Date does, that's just a bug.

**Comment by gampleman** [comment]
@icambron do you want me to make a separate issue about that?

**Comment by icambron** [comment]
@gampleman yes please

**Comment by icambron** [comment]
See also #299

**Comment by neversaid** [comment]
@icambron this is fixed by #576 as well

**Comment by icambron** [comment]
Well, sort of. It fixes the problem where we don't know the date is invalid. It doesn't fix the problem where we don't give people a way to rail the date. But I do think I'm going to close it for the same reason I closed #299.
